lib/django_openid_auth/example_consumer/urls.py
# django-openid-auth -  OpenID integration for django.contrib.auth
#
# Copyright (C) 2007 Simon Willison
# Copyright (C) 2008-2010 Canonical Ltd.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

from django.conf.urls.defaults import *
from django.contrib import admin

import views


admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', views.index),
    (r'^openid/', include('django_openid_auth.urls')),
    (r'^logout/$', 'django.contrib.auth.views.logout'),
    (r'^private/$', views.require_authentication),

    (r'^admin/(.*)', admin.site.root),
)

notes/urls.py
#
# Copyright (c) 2009 Brad Taylor <brad@getcoded.net>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.conf.urls.defaults import *
from snowy.notes.models import Note

urlpatterns = patterns('',
    url(r'^$', 'snowy.notes.views.note_index', name='note_index'),
    url(r'^list/$', 'snowy.notes.views.note_list', name='note_list'),
    url(r'^(?P<note_id>\d+)/$', 'snowy.notes.views.note_detail', name='note_detail_no_slug'),
    url(r'^(?P<note_id>\d+)/(?P<slug>[^/]+)/$', 'snowy.notes.views.note_detail', name='note_detail'),
    url(r'^notebooks/(?P<notebook_id>\d+)/(?P<slug>[^/]+)/$', 'snowy.notes.views.notebook_detail', name='notebook_detail'),
)

urls.py
#
# Copyright (c) 2009 Brad Taylor <brad@getcoded.net>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.views.generic.simple import direct_to_template, redirect_to
from django.core.urlresolvers import reverse
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

handler500 = 'snowy.views.server_error'

urlpatterns = patterns('',
    url(r'^$', direct_to_template, {'template': 'index.html'},
        name='snowy_index'),

    (r'^api/', include('snowy.api.urls')),
    (r'^accounts/', include('snowy.accounts.urls')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    (r'^export/', include('snowy.export.urls')),

    (r'^mobile/', include('snowy.mobile_notes.urls')),

    url(r'^(?P<username>\w+)/$', 'snowy.views.user_index', name="user_index"),
    (r'^(?P<username>\w+)/notes/', include('snowy.notes.urls')),
)

from django.conf import settings

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True
        }))

# OAuth
urlpatterns += patterns('piston.authentication',
    url(r'^oauth/request_token/$', 'oauth_request_token', name='oauth_request_token'),
    url(r'^oauth/authenticate/$', 'oauth_user_auth', name='oauth_user_auth'),
    url(r'^oauth/access_token/$', 'oauth_access_token', name='oauth_access_token'),
)

notes/models.py
#
# Copyright (c) 2009 Brad Taylor <brad@getcoded.net>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.db import models

from autoslug.fields import AutoSlugField

from snowy.notes.managers import NoteManager

class Note(models.Model):
    NOTE_PERMISSIONS = (
        (0, _(u'Private')), (1, _(u'Public')),
    )

    guid = models.CharField(max_length=36)

    author = models.ForeignKey(User)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    user_modified = models.DateTimeField(auto_now_add=True)

    title = models.TextField(blank=True)
    slug = AutoSlugField(unique_with='author', populate_from='title',
                         editable=True)
    content = models.TextField(blank=True)
    content_version = models.CharField(max_length=10, blank=True)

    tags = models.ManyToManyField('NoteTag', null=True, blank=True)
    permissions = models.IntegerField(choices=NOTE_PERMISSIONS,
                                      default=0)

    open_on_startup = models.BooleanField(default=False)
    pinned = models.BooleanField(default=False)

    last_sync_rev = models.IntegerField(default=-1)

    objects = NoteManager()

    class Meta:
        get_latest_by = 'user_modified'
        unique_together = (('author', 'guid'), )

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        if self.slug == "":
            return ('note_detail_no_slug', (), {
                'note_id': self.id,
                'username': self.author.username,
            })
        else:
            return ('note_detail', (), {
                'note_id': self.id,
                'username': self.author.username,
                'slug': self.slug,
            })


class NoteTag(models.Model):
    author = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    is_notebook = models.BooleanField(default=False)

    class Meta:
        unique_together = ('author', 'name')

    def __unicode__(self):
        return self.name

    def _note_is_public(self):
        # This will need to be expanded once a more
        # fine-grained permissions system is in place.
        if self.note_set.filter(permissions__gt=0).count():
            return True
        else:
            return False

    def get_name_for_display(self):
        if self.is_notebook:
            return self.name.split(':', 2)[-1]
        return self.name

    is_public = property(_note_is_public)

def _update_is_notebook(sender, instance, **kwargs):
    """
    Update is_notebook based upon the NoteTag name.
    """
    instance.is_notebook = instance.name.startswith('system:notebook:')

pre_save.connect(_update_is_notebook, sender=NoteTag,
                 dispatch_uid='snowy.notes.models.NoteTag')

notes/views.py
#
# Copyright (c) 2009 Brad Taylor <brad@getcoded.net>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.http import HttpResponseRedirect, HttpResponseForbidden, Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.template import RequestContext
from django.db.models import Q

from snowy.notes.utils  import note_to_html
from snowy.notes.models import *

def note_index(request, username,
               template_name='notes/note_index.html'):
    author = get_object_or_404(User, username=username)
    enabled = author.is_active

    # TODO: retrieve the last open note from the user
    last_modified = Note.objects.user_viewable(request.user, author) \
                                .order_by('-user_modified')
    if last_modified.count() > 0:
        return HttpResponseRedirect(last_modified[0].get_absolute_url())

    # TODO: Instruction page to tell user to either sync or create a new note
    return render_to_response(template_name,
                              {'author': author,
                               'enabled': enabled,
                               # Django 1.1 does not support == operator, so
                               # we need to do the check here and pass it along
                               'author_is_user': username==request.user.username},
                              context_instance=RequestContext(request))

def note_list(request, username,
              template_name='notes/note_list.html'):
    author = get_object_or_404(User, username=username)
    notes = Note.objects.user_viewable(request.user, author)
    return render_to_response(template_name,
                              {'notes': notes,
                               'author': author},
                              context_instance=RequestContext(request))

def notebook_detail(request, username, notebook_id, slug,
                template_name='notes/note_list.html'):
    author = get_object_or_404(User, username=username)
    notebook = get_object_or_404(NoteTag, pk=notebook_id)
    notes = Note.objects.user_viewable(request.user, author).filter(tags__in=[notebook]).order_by("-modified")
    return render_to_response(template_name,
                              {'notes': notes,
                               'author': author,
                               'username': username,
                               'notebook': notebook},
                              context_instance=RequestContext(request))

def note_detail(request, username, note_id, slug='',
                template_name='notes/note_detail.html'):
    author = get_object_or_404(User, username=username)
    note = get_object_or_404(Note, pk=note_id, author=author)

    if request.user != author and note.permissions == 0:
        return HttpResponseForbidden()

    if note.slug != slug:
        return HttpResponseRedirect(note.get_absolute_url())

    body = note_to_html(note, author)

    try:
        # Get the notebook name, if any
        notebook = note.tags.get(is_notebook=True)
        if notebook:
            notebook = notebook.get_name_for_display()
    except ObjectDoesNotExist:
        notebook = []

    return render_to_response(template_name,
                              {'title': note.title,  'note': note,
                               'notebook': notebook, 'body': body,
                               'request': request, 'author': author},
                              context_instance=RequestContext(request))

notes/templates/notes/base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block sidebar %}
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/sidebar.css" media="screen">
{% if author %}
<form method="GET" name="searchForm" action="">
    {% if request.GET.query %}
    <input type="text" id="search" name="query" accesskey="s" value="{{request.GET.query}}">
    {% else %}
    <input type="text" id="search" class="dim" name="query" accesskey="s" placeholder="{% trans "Search your notes" %}" value="{% trans "Search your notes" %}">
    {% endif %}
</form>
{% endif %}
{% endblock %}

{% block extra_body %}
<script type="text/javascript">
$(document).ready(function() {
    var undim = function () {
        $("#search").removeClass("dim")
                    .val("")
                    .unbind("focus", undim);
    }

    if($("#search").attr('class') == "dim") {
        $("#search").bind("focus", undim);
    }

    $('#search').keyup(function(e) {
        // enter key
        if (e.keyCode == 13) {
            document.searchForm.submit();
        }
    });
});
</script>
{% endblock %}

notes/templates/notes/note_detail.html
{% extends 'notes/base.html' %}

{% load i18n %}
{% load notes %}

{% block extra_head %}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/DUI.js" charset="utf-8"></script>
{# Disable funcooker for now #}
{% comment %}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/funcooker.js" charset="utf-8"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.scrollfollow.js" charset="utf-8"></script>
{% endcomment %}
{% endblock %}

{% block title %}{{ title|safe }} | Notes | {{ block.super }}{% endblock %}

{% block sidebar %}
{{ block.super }}
{% user_notes_list request author as list_notes %}
<div id="sidebar-note-list">
    <h3><a href="{% url note_list author.username %}">All Notes</a></h3>
    <h3>Recent Notes</h3>
    <ul>
        {% for n in list_notes %}
        {% if not n.pinned %}
        <li class="note-item{% if n.pinned %} pinned{% endif %}{% ifequal n note %} note-selected{% endifequal %}"><a href="{{ n.get_absolute_url }}{% if request.GET.query %}?query={{request.GET.query}}{% endif %}">{{ n.title|safe }}</a></li>
        {% endif %}
        {% endfor %}
    {% if request.GET.query %}
    <div style="text-align: center; margin: 3px;">
        <a href="."><input type="button" value="{% trans "Clear Search" %}" style="width:90%;"></a>
    </div>
    {% endif %}
    </ul>
    <ul>
{# Enable when we allow editing #}
{% comment %}
        <li id="new-note"><a href="#">New Note...</a></li>
{% endcomment %}
    </ul>
</div>
<div id="sidebar-pinned-notes-list">
    <h3>{% trans "Pinned Notes" %}</h3>
    <ul>
        {% for n in list_notes %}
        {% if n.pinned %}
        <li class="note-item note-pinned{% ifequal n note %} note-selected{% endifequal %}"><a href="{{ n.get_absolute_url }}{% if request.GET.query %}?query={{request.GET.query}}{% endif %}">{{ n.title|safe }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

<div id="sidebar-shared-notes-list">
    <h3>{% trans "Other's Notes" %}</h3>
</div>

<div id="sidebar-notebook-list">
    <h3>{% trans "Notebooks" %}</h3>
    <ul>
{% user_notebook_list request author as all_notebooks %}
{% include "notes/notebook_list_snippet.html" %}
    </ul>
</div>
{% endblock %}

{% block content-header %}
{# Enable when we allow editing/sharing, but only when user has permission on this note #}
{% comment %}
<div id="note-header">
    <button class="header-button">Share</button>
    <button class="header-button">Delete</button>
    <button class="header-button" style="float:right;">Edit</button>
</div>
{% endcomment %}
{% endblock %}
{% block content %}
<table id="content-layout" cellspacing="0" cellpadding="0">
    {% if notebook or request.user != author %}
    <tr><td>
        {# FIXME: Proper l10n for "'s" #}
        <span id="breadcrumb">{% if request.user != author %}<a href="{% url user_index author.username %}">{{ author.username }}{% trans "'s" %}</a> {% trans "Notes" %} &raquo; {% endif %}{% if notebook %}{{ notebook|safe }} &raquo; {% endif %}{{ title|safe }}</span>
    </td></tr>
    {% endif %}
    <tr>
        <td id="note">
            <h1>{{ title|safe }}</h1>
            <div id="funcooker">
                {{ body|safe }}
            </div>
        </td>
        <td>
{# Disable funcooker for now #}
{% comment %}
            <div id="toolbar">
                <h3>Text</h3>
                <p id="toolbar-text">
                    <a href="javascript:fc.normalStyle();" title="Normal">A</a>
                    <a href="javascript:fc.bold();" title="Bold"><b>A</b></a>
                    <a href="javascript:fc.strikethrough();" title="Strikethrough"><strike>A</strike></a>
                    <a href="javascript:fc.highlight();" title="Highlight"><span class="note-highlight">A</span></a>
                    <a href="javascript:fc.fixedWidth();" title="Fixed Width"><span class="note-monospace">A</span></a>
                </p>
                <h3>Font Size</h3>
                <p class="note-small"><a href="javascript:fc.small();">Small</a></p>
                <p><a href="javascript:fc.normalSize();">Normal</a></p>
                <p class="note-large"><a href="javascript:fc.large();">Large</a></p>
                <p class="note-huge"><a href="javascript:fc.huge();">Huge</a></p>
                <h3>Formatting</h3>
                <p><a href="#">Bullets</a></p>
                <p><a href="#">Increase Indent</a></p>
                <p><a href="#">Decrease Indent</a></p>
                <h3>Actions</h3>
                <p><a href="#">Link</a></p>
                <p><a href="#">Delete</a></p>
                <p><a href="#">History</a></p>
                <p><a href="#">Sharing</a></p>
            </div>
{% endcomment %}
        </td>
    </tr>
</table>
{% comment %}
<script type="text/javascript">
var fc = null;
$(document).ready(function() {
    fc = new FunCooker("#funcooker");

    $('#toolbar').scrollFollow({
        speed: 200,
        offset: 10,
        container: 'content',
    });
});
</script>
{% endcomment %}
{% endblock %}

notes/templates/notes/note_index.html
{% extends 'notes/base.html' %}

{% load i18n %}
{% load notes %}

{% block extra_head %}
{% endblock %}

{% block title %}{{ title|safe }} | Notes | {{ block.super }}{% endblock %}

{% block sidebar %}
{{ block.super }}
{% user_notes_list request author as all_notes %}
<div id="sidebar-note-list">
    {% if enabled %}
    <ul>
{% for n in all_notes %}
        <li class="note-item{% if n.pinned %} pinned{% endif %}"><a href="{{ n.get_absolute_url }}">{{ n.title|safe }}</a></li>
{% endfor %}
    </ul>
    <hr />
    <ul>
{# Enable when we allow editing #}
{% comment %}
        <li id="new-note"><a href="#">New Note...</a></li>
{% endcomment %}
    </ul>
    {% endif %}
</div>
<div id="sidebar-notebook-list">
{% if enabled %}
    <h3>{% trans "Notebooks" %}</h3>
    <ul>
{% user_notebook_list request author as all_notebooks %}
{% include "notes/notebook_list_snippet.html" %}
{% endif %}
{% endblock %}

{% block content %}
{% if enabled %}
<table id="content-layout" cellspacing="0" cellpadding="0">
    <tr>
        <td id="note">
            {% comment %}
            Django 1.1 does not support == operator, so we can't do:
               if author == request.user
            {% endcomment %}
            {% if author_is_user %}
            <h1>{% trans "Notice" %}</h1>
            <div id="funcooker">
                {% trans "You haven't synced any notes with Snowy yet." %}
            </div>
            {% else %}
            <h1>{% trans "Notice" %}</h1>
            <div id="funcooker">
                {% trans "This user is not sharing any notes with you." %}
            </div>
            {% endif %}
        </td>
        <td>
        </td>
    </br>
</table>
{% else %}
<h1>Notice</h1>
{{ author }}'s account is currently disabled.
{% endif %}
{% endblock %}

notes/templates/notes/note_list.html
{% extends 'notes/note_detail.html' %}

{% load i18n %}

{% block title %}{% trans "All Notes" %} | {{ block.super }}{% endblock %}

{% block content %}
{% include "notes/note_list_snippet.html" %}
{% endblock %}

notes/templates/notes/note_list_snippet.html
{% load i18n %}{% load humanize %}{% load pagination_tags %}
{% if notebook %}
<h1>{% trans "All notes for" %} {{ notebook.get_name_for_display }}</h1>
{% endif %}
<table class="object_list" cellspacing="0" cellpadding="0">
    <thead>
        <tr>
            <th></th>
            <th>{% trans "Title" %}</th>
            <th>{% trans "Last Modified" %}</th>
            <th>{% trans "Visibility" %}</th>
        </tr>
    </thead>
    <tbody>
{% autopaginate notes %}
{% for note in notes %}
        <tr class="note-list-row">
{% if note.pinned %}
            <td class="icon"><img src="{{ MEDIA_URL }}img/pin-down_16.png" width="16" height="16" alt="Pinned"/></td>
{% else %}
            <td class="icon"><img src="{{ MEDIA_URL }}img/note_16.png" width="16" height="16" alt="Not pinned"/></td>
{% endif %}
            <td><a href="{{ note.get_absolute_url }}">{{ note.title|safe }}</a></td>
            <td>{{ note.user_modified|naturalday|title }}</td>
            <td>{{ note.get_permissions_display }}</td>
        </tr>
{% endfor %}
    </tbody>
    <tfoot>
        <tr>
{% ifnotequal paginator.num_pages 1 %}
            <td colspan="4">{% paginate %}</td>
{% else %}
            <td colspan="4">{% blocktrans count paginator.count as c %}{{ c }} result found{% plural %}{{ c }} results found{% endblocktrans %}</td>
{% endifnotequal %}
        </tr>
    </tfoot>
</table>

notes/templates/notes/notebook_list_snippet.html
{% comment %}In the spirit of D.R.Y.{% endcomment %}
{% for n in all_notebooks %}
  {# This grossness goes away with django 1.2's smarter if tags #}
  {% if n.is_public %}<li class="notebook-item"><a href="{% url notebook_detail n.author n.pk n.get_name_for_display|slugify %}">{{ n.get_name_for_display }}</a></li>
  {% else %}{% ifequal request.user n.author %}<li class="notebook-item"><a href="{% url notebook_detail n.author n.pk n.get_name_for_display|slugify %}">{{ n.get_name_for_display }}</a></li>{% endifequal %}
  {% endif %}
{% endfor %}